# This file serves as the agent configuration to interact with the
# docker compose environment.
#
# You should pass the following command line flags when running the agent
# locally and using this file:
#
#   -enable-features=integrations-next -config.expand-env -config.enable-read-api
#
# -enable-features=integrations-next is required as the file is configured for
# the integrations revamp.
#
# -config.expand-env is required to expand environment variables. Environment
# variables are used when running the agent inside of docker-compose to connect
# to the other services. When running the agent externally, the expressions will
# default to the appropriate values of the exposed ports.
#
# -config.enable-read-api is optional, but allows you to invoke the /-/config
# endpoint to examine the generated config.

server:
  log_level: debug
#  http_listen_port: 12345

logs:
  configs:
  - name: default
    clients:
      - url: http://${LOKI_HOST}/loki/api/v1/push
    positions:
      filename: /tmp/positions.yaml
    scrape_configs:
    - job_name: pet-clinic
      static_configs:
      - targets: [localhost]
        labels:
          job: pet-clinic
          __path__: /tmp/pet-clinic.log
    - job_name: tomcat-log
      static_configs:
      - targets: [localhost]
        labels:
          job: tomcat-log
          __path__: /tmp/tomcat_log.log

traces:
  configs:
  - name: default
    remote_write:
      - endpoint: http://tempo:4317
        insecure: true

    receivers:
      otlp:
        protocols:
          grpc:
#          http:
#            endpoint: "0.0.0.0:4318"
#            cors:
#              allowed_origins: 
#                - http://localhost:8080
#              allowed_headers: ["*"]
