global:
  scrape_interval:     10s
  external_labels:
    monitor: pet-clinic

scrape_configs:
  - job_name: pet-clinic
    scrape_interval: 10s
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [spring-petclinic:8080]